mysql_root_password: kM23aJATjthV
mysql_databases:
  - name: wordpress
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: wordpress
    host: "%"
    password: 7uZRUgvsbBmn
    priv: "wordpress.*:ALL"



#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

#HTTP Settings
http_host: "iwd"
http_conf: "iwd.conf"
http_port: "80"